//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyNhanKhauEntities : DbContext
    {
        public QuanLyNhanKhauEntities()
            : base("name=QuanLyNhanKhauEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_CSKV> tb_CSKV { get; set; }
        public virtual DbSet<tb_ChuHo> tb_ChuHo { get; set; }
        public virtual DbSet<tb_HoGiaDinh> tb_HoGiaDinh { get; set; }
        public virtual DbSet<tb_KhuPho> tb_KhuPho { get; set; }
        public virtual DbSet<tb_PhuongXa> tb_PhuongXa { get; set; }
        public virtual DbSet<tb_Quan> tb_Quan { get; set; }
        public virtual DbSet<tb_ToTruongKhuPho> tb_ToTruongKhuPho { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_ChinhSuaChuHo(Nullable<int> iDChuHo, Nullable<int> iDKhuPho, string hoTenChuHo, string diaChi, string thongTinLienHe, Nullable<bool> conSong)
        {
            var iDChuHoParameter = iDChuHo.HasValue ?
                new ObjectParameter("IDChuHo", iDChuHo) :
                new ObjectParameter("IDChuHo", typeof(int));
    
            var iDKhuPhoParameter = iDKhuPho.HasValue ?
                new ObjectParameter("IDKhuPho", iDKhuPho) :
                new ObjectParameter("IDKhuPho", typeof(int));
    
            var hoTenChuHoParameter = hoTenChuHo != null ?
                new ObjectParameter("HoTenChuHo", hoTenChuHo) :
                new ObjectParameter("HoTenChuHo", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var thongTinLienHeParameter = thongTinLienHe != null ?
                new ObjectParameter("ThongTinLienHe", thongTinLienHe) :
                new ObjectParameter("ThongTinLienHe", typeof(string));
    
            var conSongParameter = conSong.HasValue ?
                new ObjectParameter("ConSong", conSong) :
                new ObjectParameter("ConSong", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaChuHo", iDChuHoParameter, iDKhuPhoParameter, hoTenChuHoParameter, diaChiParameter, thongTinLienHeParameter, conSongParameter);
        }
    
        public virtual int sp_ChinhSuaCSKV(Nullable<int> iDCSKV, Nullable<int> iDKhuPho, string hoTen, string chucVu, string thongTinLienHe, Nullable<System.DateTime> ngayThamGiaCongTac, Nullable<bool> trangThai)
        {
            var iDCSKVParameter = iDCSKV.HasValue ?
                new ObjectParameter("IDCSKV", iDCSKV) :
                new ObjectParameter("IDCSKV", typeof(int));
    
            var iDKhuPhoParameter = iDKhuPho.HasValue ?
                new ObjectParameter("IDKhuPho", iDKhuPho) :
                new ObjectParameter("IDKhuPho", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var thongTinLienHeParameter = thongTinLienHe != null ?
                new ObjectParameter("ThongTinLienHe", thongTinLienHe) :
                new ObjectParameter("ThongTinLienHe", typeof(string));
    
            var ngayThamGiaCongTacParameter = ngayThamGiaCongTac.HasValue ?
                new ObjectParameter("NgayThamGiaCongTac", ngayThamGiaCongTac) :
                new ObjectParameter("NgayThamGiaCongTac", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaCSKV", iDCSKVParameter, iDKhuPhoParameter, hoTenParameter, chucVuParameter, thongTinLienHeParameter, ngayThamGiaCongTacParameter, trangThaiParameter);
        }
    
        public virtual int sp_ChinhSuaHoGiaDinh(Nullable<int> iDHoGiaDinh, Nullable<int> iDChuHo, string hoTen, string ngheNghiep, string gioiTinh, string quanHeChuHo, Nullable<bool> conSong)
        {
            var iDHoGiaDinhParameter = iDHoGiaDinh.HasValue ?
                new ObjectParameter("IDHoGiaDinh", iDHoGiaDinh) :
                new ObjectParameter("IDHoGiaDinh", typeof(int));
    
            var iDChuHoParameter = iDChuHo.HasValue ?
                new ObjectParameter("IDChuHo", iDChuHo) :
                new ObjectParameter("IDChuHo", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var ngheNghiepParameter = ngheNghiep != null ?
                new ObjectParameter("NgheNghiep", ngheNghiep) :
                new ObjectParameter("NgheNghiep", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var quanHeChuHoParameter = quanHeChuHo != null ?
                new ObjectParameter("QuanHeChuHo", quanHeChuHo) :
                new ObjectParameter("QuanHeChuHo", typeof(string));
    
            var conSongParameter = conSong.HasValue ?
                new ObjectParameter("ConSong", conSong) :
                new ObjectParameter("ConSong", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaHoGiaDinh", iDHoGiaDinhParameter, iDChuHoParameter, hoTenParameter, ngheNghiepParameter, gioiTinhParameter, quanHeChuHoParameter, conSongParameter);
        }
    
        public virtual int sp_ChinhSuaKhuPho(Nullable<int> iDKhuPho, Nullable<int> iDPhuongXa, string tenKhuPho, Nullable<int> danSo, string diaChiTruSoHanhChinh, string thongTinLienHe)
        {
            var iDKhuPhoParameter = iDKhuPho.HasValue ?
                new ObjectParameter("IDKhuPho", iDKhuPho) :
                new ObjectParameter("IDKhuPho", typeof(int));
    
            var iDPhuongXaParameter = iDPhuongXa.HasValue ?
                new ObjectParameter("IDPhuongXa", iDPhuongXa) :
                new ObjectParameter("IDPhuongXa", typeof(int));
    
            var tenKhuPhoParameter = tenKhuPho != null ?
                new ObjectParameter("TenKhuPho", tenKhuPho) :
                new ObjectParameter("TenKhuPho", typeof(string));
    
            var danSoParameter = danSo.HasValue ?
                new ObjectParameter("DanSo", danSo) :
                new ObjectParameter("DanSo", typeof(int));
    
            var diaChiTruSoHanhChinhParameter = diaChiTruSoHanhChinh != null ?
                new ObjectParameter("DiaChiTruSoHanhChinh", diaChiTruSoHanhChinh) :
                new ObjectParameter("DiaChiTruSoHanhChinh", typeof(string));
    
            var thongTinLienHeParameter = thongTinLienHe != null ?
                new ObjectParameter("ThongTinLienHe", thongTinLienHe) :
                new ObjectParameter("ThongTinLienHe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaKhuPho", iDKhuPhoParameter, iDPhuongXaParameter, tenKhuPhoParameter, danSoParameter, diaChiTruSoHanhChinhParameter, thongTinLienHeParameter);
        }
    
        public virtual int sp_ChinhSuaPhuongXa(Nullable<int> iDPhuongXa, Nullable<int> iDQuan, string tenPhuong, Nullable<int> danSo, Nullable<double> dienTich, string diaChiTruSoHanhChinh, string thongTinLienHe)
        {
            var iDPhuongXaParameter = iDPhuongXa.HasValue ?
                new ObjectParameter("IDPhuongXa", iDPhuongXa) :
                new ObjectParameter("IDPhuongXa", typeof(int));
    
            var iDQuanParameter = iDQuan.HasValue ?
                new ObjectParameter("IDQuan", iDQuan) :
                new ObjectParameter("IDQuan", typeof(int));
    
            var tenPhuongParameter = tenPhuong != null ?
                new ObjectParameter("TenPhuong", tenPhuong) :
                new ObjectParameter("TenPhuong", typeof(string));
    
            var danSoParameter = danSo.HasValue ?
                new ObjectParameter("DanSo", danSo) :
                new ObjectParameter("DanSo", typeof(int));
    
            var dienTichParameter = dienTich.HasValue ?
                new ObjectParameter("DienTich", dienTich) :
                new ObjectParameter("DienTich", typeof(double));
    
            var diaChiTruSoHanhChinhParameter = diaChiTruSoHanhChinh != null ?
                new ObjectParameter("DiaChiTruSoHanhChinh", diaChiTruSoHanhChinh) :
                new ObjectParameter("DiaChiTruSoHanhChinh", typeof(string));
    
            var thongTinLienHeParameter = thongTinLienHe != null ?
                new ObjectParameter("ThongTinLienHe", thongTinLienHe) :
                new ObjectParameter("ThongTinLienHe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaPhuongXa", iDPhuongXaParameter, iDQuanParameter, tenPhuongParameter, danSoParameter, dienTichParameter, diaChiTruSoHanhChinhParameter, thongTinLienHeParameter);
        }
    
        public virtual int sp_ChinhSuaQuan(Nullable<int> iDQuan, string tenQuan, string thanhPho_Tinh, Nullable<int> danSo, Nullable<double> dienTich, string diaChiKhuPhoHanhChinh, string thongTinLienHe)
        {
            var iDQuanParameter = iDQuan.HasValue ?
                new ObjectParameter("IDQuan", iDQuan) :
                new ObjectParameter("IDQuan", typeof(int));
    
            var tenQuanParameter = tenQuan != null ?
                new ObjectParameter("TenQuan", tenQuan) :
                new ObjectParameter("TenQuan", typeof(string));
    
            var thanhPho_TinhParameter = thanhPho_Tinh != null ?
                new ObjectParameter("ThanhPho_Tinh", thanhPho_Tinh) :
                new ObjectParameter("ThanhPho_Tinh", typeof(string));
    
            var danSoParameter = danSo.HasValue ?
                new ObjectParameter("DanSo", danSo) :
                new ObjectParameter("DanSo", typeof(int));
    
            var dienTichParameter = dienTich.HasValue ?
                new ObjectParameter("DienTich", dienTich) :
                new ObjectParameter("DienTich", typeof(double));
    
            var diaChiKhuPhoHanhChinhParameter = diaChiKhuPhoHanhChinh != null ?
                new ObjectParameter("DiaChiKhuPhoHanhChinh", diaChiKhuPhoHanhChinh) :
                new ObjectParameter("DiaChiKhuPhoHanhChinh", typeof(string));
    
            var thongTinLienHeParameter = thongTinLienHe != null ?
                new ObjectParameter("ThongTinLienHe", thongTinLienHe) :
                new ObjectParameter("ThongTinLienHe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaQuan", iDQuanParameter, tenQuanParameter, thanhPho_TinhParameter, danSoParameter, dienTichParameter, diaChiKhuPhoHanhChinhParameter, thongTinLienHeParameter);
        }
    
        public virtual int sp_ChinhSuaToTruongKhuPho(Nullable<int> iDToTruong, Nullable<int> iDKhuPho, string tenToTruong, Nullable<System.DateTime> ngaySinh, string gioiTinh, string diaChiCuTru, Nullable<System.DateTime> ngayBatDau, Nullable<bool> trangThai, string thongTinLienHe)
        {
            var iDToTruongParameter = iDToTruong.HasValue ?
                new ObjectParameter("IDToTruong", iDToTruong) :
                new ObjectParameter("IDToTruong", typeof(int));
    
            var iDKhuPhoParameter = iDKhuPho.HasValue ?
                new ObjectParameter("IDKhuPho", iDKhuPho) :
                new ObjectParameter("IDKhuPho", typeof(int));
    
            var tenToTruongParameter = tenToTruong != null ?
                new ObjectParameter("TenToTruong", tenToTruong) :
                new ObjectParameter("TenToTruong", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var diaChiCuTruParameter = diaChiCuTru != null ?
                new ObjectParameter("DiaChiCuTru", diaChiCuTru) :
                new ObjectParameter("DiaChiCuTru", typeof(string));
    
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            var thongTinLienHeParameter = thongTinLienHe != null ?
                new ObjectParameter("ThongTinLienHe", thongTinLienHe) :
                new ObjectParameter("ThongTinLienHe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaToTruongKhuPho", iDToTruongParameter, iDKhuPhoParameter, tenToTruongParameter, ngaySinhParameter, gioiTinhParameter, diaChiCuTruParameter, ngayBatDauParameter, trangThaiParameter, thongTinLienHeParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_ThemChuHo(Nullable<int> iDKhuPho, string hoTenChuHo, string diaChi, string thongTinLienHe, Nullable<bool> conSong)
        {
            var iDKhuPhoParameter = iDKhuPho.HasValue ?
                new ObjectParameter("IDKhuPho", iDKhuPho) :
                new ObjectParameter("IDKhuPho", typeof(int));
    
            var hoTenChuHoParameter = hoTenChuHo != null ?
                new ObjectParameter("HoTenChuHo", hoTenChuHo) :
                new ObjectParameter("HoTenChuHo", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var thongTinLienHeParameter = thongTinLienHe != null ?
                new ObjectParameter("ThongTinLienHe", thongTinLienHe) :
                new ObjectParameter("ThongTinLienHe", typeof(string));
    
            var conSongParameter = conSong.HasValue ?
                new ObjectParameter("ConSong", conSong) :
                new ObjectParameter("ConSong", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemChuHo", iDKhuPhoParameter, hoTenChuHoParameter, diaChiParameter, thongTinLienHeParameter, conSongParameter);
        }
    
        public virtual int sp_ThemCSKV(Nullable<int> iDKhuPho, string hoTen, string chucVu, string thongTinLienHe, Nullable<System.DateTime> ngayThamGiaCongTac, Nullable<bool> trangThai)
        {
            var iDKhuPhoParameter = iDKhuPho.HasValue ?
                new ObjectParameter("IDKhuPho", iDKhuPho) :
                new ObjectParameter("IDKhuPho", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var thongTinLienHeParameter = thongTinLienHe != null ?
                new ObjectParameter("ThongTinLienHe", thongTinLienHe) :
                new ObjectParameter("ThongTinLienHe", typeof(string));
    
            var ngayThamGiaCongTacParameter = ngayThamGiaCongTac.HasValue ?
                new ObjectParameter("NgayThamGiaCongTac", ngayThamGiaCongTac) :
                new ObjectParameter("NgayThamGiaCongTac", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemCSKV", iDKhuPhoParameter, hoTenParameter, chucVuParameter, thongTinLienHeParameter, ngayThamGiaCongTacParameter, trangThaiParameter);
        }
    
        public virtual int sp_ThemHoGiaDinh(Nullable<int> iDChuHo, string hoTen, string ngheNghiep, string gioiTinh, string quanHeChuHo, Nullable<bool> conSong)
        {
            var iDChuHoParameter = iDChuHo.HasValue ?
                new ObjectParameter("IDChuHo", iDChuHo) :
                new ObjectParameter("IDChuHo", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var ngheNghiepParameter = ngheNghiep != null ?
                new ObjectParameter("NgheNghiep", ngheNghiep) :
                new ObjectParameter("NgheNghiep", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var quanHeChuHoParameter = quanHeChuHo != null ?
                new ObjectParameter("QuanHeChuHo", quanHeChuHo) :
                new ObjectParameter("QuanHeChuHo", typeof(string));
    
            var conSongParameter = conSong.HasValue ?
                new ObjectParameter("ConSong", conSong) :
                new ObjectParameter("ConSong", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemHoGiaDinh", iDChuHoParameter, hoTenParameter, ngheNghiepParameter, gioiTinhParameter, quanHeChuHoParameter, conSongParameter);
        }
    
        public virtual int sp_ThemKhuPho(Nullable<int> iDPhuongXa, string tenKhuPho, Nullable<int> danSo, string diaChiTruSoHanhChinh, string thongTinLienHe)
        {
            var iDPhuongXaParameter = iDPhuongXa.HasValue ?
                new ObjectParameter("IDPhuongXa", iDPhuongXa) :
                new ObjectParameter("IDPhuongXa", typeof(int));
    
            var tenKhuPhoParameter = tenKhuPho != null ?
                new ObjectParameter("TenKhuPho", tenKhuPho) :
                new ObjectParameter("TenKhuPho", typeof(string));
    
            var danSoParameter = danSo.HasValue ?
                new ObjectParameter("DanSo", danSo) :
                new ObjectParameter("DanSo", typeof(int));
    
            var diaChiTruSoHanhChinhParameter = diaChiTruSoHanhChinh != null ?
                new ObjectParameter("DiaChiTruSoHanhChinh", diaChiTruSoHanhChinh) :
                new ObjectParameter("DiaChiTruSoHanhChinh", typeof(string));
    
            var thongTinLienHeParameter = thongTinLienHe != null ?
                new ObjectParameter("ThongTinLienHe", thongTinLienHe) :
                new ObjectParameter("ThongTinLienHe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemKhuPho", iDPhuongXaParameter, tenKhuPhoParameter, danSoParameter, diaChiTruSoHanhChinhParameter, thongTinLienHeParameter);
        }
    
        public virtual int sp_ThemPhuongXa(Nullable<int> iDQuan, string tenPhuong, Nullable<int> danSo, Nullable<double> dienTich, string diaChiTruSoHanhChinh, string thongTinLienHe)
        {
            var iDQuanParameter = iDQuan.HasValue ?
                new ObjectParameter("IDQuan", iDQuan) :
                new ObjectParameter("IDQuan", typeof(int));
    
            var tenPhuongParameter = tenPhuong != null ?
                new ObjectParameter("TenPhuong", tenPhuong) :
                new ObjectParameter("TenPhuong", typeof(string));
    
            var danSoParameter = danSo.HasValue ?
                new ObjectParameter("DanSo", danSo) :
                new ObjectParameter("DanSo", typeof(int));
    
            var dienTichParameter = dienTich.HasValue ?
                new ObjectParameter("DienTich", dienTich) :
                new ObjectParameter("DienTich", typeof(double));
    
            var diaChiTruSoHanhChinhParameter = diaChiTruSoHanhChinh != null ?
                new ObjectParameter("DiaChiTruSoHanhChinh", diaChiTruSoHanhChinh) :
                new ObjectParameter("DiaChiTruSoHanhChinh", typeof(string));
    
            var thongTinLienHeParameter = thongTinLienHe != null ?
                new ObjectParameter("ThongTinLienHe", thongTinLienHe) :
                new ObjectParameter("ThongTinLienHe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemPhuongXa", iDQuanParameter, tenPhuongParameter, danSoParameter, dienTichParameter, diaChiTruSoHanhChinhParameter, thongTinLienHeParameter);
        }
    
        public virtual int sp_ThemQuan(string tenQuan, string thanhPho_Tinh, Nullable<int> danSo, Nullable<double> dienTich, string diaChiKhuPhoHanhChinh, string thongTinLienHe)
        {
            var tenQuanParameter = tenQuan != null ?
                new ObjectParameter("TenQuan", tenQuan) :
                new ObjectParameter("TenQuan", typeof(string));
    
            var thanhPho_TinhParameter = thanhPho_Tinh != null ?
                new ObjectParameter("ThanhPho_Tinh", thanhPho_Tinh) :
                new ObjectParameter("ThanhPho_Tinh", typeof(string));
    
            var danSoParameter = danSo.HasValue ?
                new ObjectParameter("DanSo", danSo) :
                new ObjectParameter("DanSo", typeof(int));
    
            var dienTichParameter = dienTich.HasValue ?
                new ObjectParameter("DienTich", dienTich) :
                new ObjectParameter("DienTich", typeof(double));
    
            var diaChiKhuPhoHanhChinhParameter = diaChiKhuPhoHanhChinh != null ?
                new ObjectParameter("DiaChiKhuPhoHanhChinh", diaChiKhuPhoHanhChinh) :
                new ObjectParameter("DiaChiKhuPhoHanhChinh", typeof(string));
    
            var thongTinLienHeParameter = thongTinLienHe != null ?
                new ObjectParameter("ThongTinLienHe", thongTinLienHe) :
                new ObjectParameter("ThongTinLienHe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemQuan", tenQuanParameter, thanhPho_TinhParameter, danSoParameter, dienTichParameter, diaChiKhuPhoHanhChinhParameter, thongTinLienHeParameter);
        }
    
        public virtual int sp_ThemToTruongKhuPho(Nullable<int> iDKhuPho, string tenToTruong, Nullable<System.DateTime> ngaySinh, string gioiTinh, string diaChiCuTru, Nullable<System.DateTime> ngayBatDau, Nullable<bool> trangThai, string thongTinLienHe)
        {
            var iDKhuPhoParameter = iDKhuPho.HasValue ?
                new ObjectParameter("IDKhuPho", iDKhuPho) :
                new ObjectParameter("IDKhuPho", typeof(int));
    
            var tenToTruongParameter = tenToTruong != null ?
                new ObjectParameter("TenToTruong", tenToTruong) :
                new ObjectParameter("TenToTruong", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var diaChiCuTruParameter = diaChiCuTru != null ?
                new ObjectParameter("DiaChiCuTru", diaChiCuTru) :
                new ObjectParameter("DiaChiCuTru", typeof(string));
    
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            var thongTinLienHeParameter = thongTinLienHe != null ?
                new ObjectParameter("ThongTinLienHe", thongTinLienHe) :
                new ObjectParameter("ThongTinLienHe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemToTruongKhuPho", iDKhuPhoParameter, tenToTruongParameter, ngaySinhParameter, gioiTinhParameter, diaChiCuTruParameter, ngayBatDauParameter, trangThaiParameter, thongTinLienHeParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sp_XoaChuHo(Nullable<int> iDChuHo, Nullable<bool> isDelete)
        {
            var iDChuHoParameter = iDChuHo.HasValue ?
                new ObjectParameter("IDChuHo", iDChuHo) :
                new ObjectParameter("IDChuHo", typeof(int));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaChuHo", iDChuHoParameter, isDeleteParameter);
        }
    
        public virtual int sp_XoaCSKV(Nullable<int> iDCSKV, Nullable<bool> isDelete)
        {
            var iDCSKVParameter = iDCSKV.HasValue ?
                new ObjectParameter("IDCSKV", iDCSKV) :
                new ObjectParameter("IDCSKV", typeof(int));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaCSKV", iDCSKVParameter, isDeleteParameter);
        }
    
        public virtual int sp_XoaHoGiaDinh(Nullable<int> iDHoGiaDinh, Nullable<bool> isDelete)
        {
            var iDHoGiaDinhParameter = iDHoGiaDinh.HasValue ?
                new ObjectParameter("IDHoGiaDinh", iDHoGiaDinh) :
                new ObjectParameter("IDHoGiaDinh", typeof(int));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaHoGiaDinh", iDHoGiaDinhParameter, isDeleteParameter);
        }
    
        public virtual int sp_XoaKhuPho(Nullable<int> iDKhuPho, Nullable<bool> isDelete)
        {
            var iDKhuPhoParameter = iDKhuPho.HasValue ?
                new ObjectParameter("IDKhuPho", iDKhuPho) :
                new ObjectParameter("IDKhuPho", typeof(int));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaKhuPho", iDKhuPhoParameter, isDeleteParameter);
        }
    
        public virtual int sp_XoaPhuongXa(Nullable<int> iDPhuongXa, Nullable<bool> isDelete)
        {
            var iDPhuongXaParameter = iDPhuongXa.HasValue ?
                new ObjectParameter("IDPhuongXa", iDPhuongXa) :
                new ObjectParameter("IDPhuongXa", typeof(int));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaPhuongXa", iDPhuongXaParameter, isDeleteParameter);
        }
    
        public virtual int sp_XoaQuan(Nullable<int> iDQuan, Nullable<bool> isDelete)
        {
            var iDQuanParameter = iDQuan.HasValue ?
                new ObjectParameter("IDQuan", iDQuan) :
                new ObjectParameter("IDQuan", typeof(int));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaQuan", iDQuanParameter, isDeleteParameter);
        }
    
        public virtual int sp_XoaToTruongKhuPho(Nullable<int> iDToTruong, Nullable<bool> isDelete)
        {
            var iDToTruongParameter = iDToTruong.HasValue ?
                new ObjectParameter("IDToTruong", iDToTruong) :
                new ObjectParameter("IDToTruong", typeof(int));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaToTruongKhuPho", iDToTruongParameter, isDeleteParameter);
        }
    }
}
