//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CSKV
    {
        public int IDCSKV { get; set; }
        public Nullable<int> IDKhuPho { get; set; }
        public string HoTen { get; set; }
        public string ChucVu { get; set; }
        public string ThongTinLienHe { get; set; }
        public Nullable<System.DateTime> NgayThamGiaCongTac { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual tb_KhuPho tb_KhuPho { get; set; }
    }
}
