//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChuHo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ChuHo()
        {
            this.tb_HoGiaDinh = new HashSet<tb_HoGiaDinh>();
        }
    
        public int IDChuHo { get; set; }
        public Nullable<int> IDKhuPho { get; set; }
        public string HoTenChuHo { get; set; }
        public string DiaChi { get; set; }
        public string ThongTinLienHe { get; set; }
        public Nullable<bool> ConSong { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual tb_KhuPho tb_KhuPho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_HoGiaDinh> tb_HoGiaDinh { get; set; }
    }
}
