//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HoGiaDinh
    {
        public int IDHoGiaDinh { get; set; }
        public Nullable<int> IDChuHo { get; set; }
        public string HoTen { get; set; }
        public string NgheNghiep { get; set; }
        public string GioiTinh { get; set; }
        public string QuanHeChuHo { get; set; }
        public Nullable<bool> ConSong { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual tb_ChuHo tb_ChuHo { get; set; }
    }
}
