//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PhuongXa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_PhuongXa()
        {
            this.tb_KhuPho = new HashSet<tb_KhuPho>();
        }
    
        public int IDPhuongXa { get; set; }
        public Nullable<int> IDQuan { get; set; }
        public string TenPhuong { get; set; }
        public Nullable<int> DanSo { get; set; }
        public Nullable<double> DienTich { get; set; }
        public string DiaChiTruSoHanhChinh { get; set; }
        public string ThongTinLienHe { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_KhuPho> tb_KhuPho { get; set; }
        public virtual tb_Quan tb_Quan { get; set; }
    }
}
