//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Quan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Quan()
        {
            this.tb_PhuongXa = new HashSet<tb_PhuongXa>();
        }
    
        public int IDQuan { get; set; }
        public string TenQuan { get; set; }
        public string ThanhPho_Tinh { get; set; }
        public Nullable<int> DanSo { get; set; }
        public Nullable<double> DienTich { get; set; }
        public string DiaChiKhuPhoHanhChinh { get; set; }
        public string ThongTinLienHe { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PhuongXa> tb_PhuongXa { get; set; }
    }
}
