//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ToTruongKhuPho
    {
        public int IDToTruong { get; set; }
        public Nullable<int> IDKhuPho { get; set; }
        public string TenToTruong { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChiCuTru { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string ThongTinLienHe { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual tb_KhuPho tb_KhuPho { get; set; }
    }
}
